#==== gfortran (current version: gcc 4.5) ====
#FC = gfortran
FC = mpif90


FCFLAGS = -O3 
#FCFLAGS = -g -O0 -Wall -fbounds-check -fbacktrace -fstack-protector-all -Wno-real-q-constant  -ffpe-trap=zero -ffpe-trap=overflow -ffpe-trap=underflow


#-- additional flags
FCFLAGS += -m64 -msse3
FCFLAGS += -fopenmp
FCFLAGS_FF = -ffixed-form
LDFLAGS = -fopenmp

AR = ar
RANLIB=ranlib
