#==== gfortran (current version: gcc 4.5) ====
#FC = gfortran
FC = mpif90


FCFLAGS = -O3 -fopenmp -march=native
#FCFLAGS = -g -Werror -O0 -Wall -fbounds-check -fbacktrace -fstack-protector-all -Wno-real-q-constant  -ffpe-trap=zero -ffpe-trap=overflow


#-- additional flags
FCFLAGS_FF = -ffixed-form
LDFLAGS = -fopenmp

AR = ar
RANLIB=ranlib
